// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TP_ProgramaciónII_PIPORAMA.Data.Models
{
    public partial class ClientesFrecuentesResult
    {
        [StringLength(80)]
        public string nom_cliente { get; set; }
        [StringLength(40)]
        public string ape_cliente { get; set; }
        public int? total_compras { get; set; }
    }
}
