// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TP_ProgramaciónII_PIPORAMA.Data.Models
{
    public partial class ConsumiblesMasVendidosResult
    {
        [StringLength(80)]
        public string nom_consumible { get; set; }
        public int? total_vendido { get; set; }
        public int? ingresos_generados { get; set; }
    }
}
