// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TP_ProgramaciónII_PIPORAMA.Data.Models;

public partial class Empleado
{
    public int IdEmpleado { get; set; }

    public string NomEmpleado { get; set; }

    public string ApeEmpleado { get; set; }

    public int IdBarrio { get; set; }

    public int IdContacto { get; set; }

    public bool Activo { get; set; }

    public virtual ICollection<Factura> Facturas { get; set; } = new List<Factura>();

    public virtual Barrio IdBarrioNavigation { get; set; }

    public virtual Contacto IdContactoNavigation { get; set; }
}