// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using TP_ProgramaciónII_PIPORAMA.Data.Models;

namespace TP_ProgramaciónII_PIPORAMA.Data.Models
{
    public partial interface IPIPORAMAContextProcedures
    {
        Task<List<SP_ClientesFrecuentesResult>> SP_ClientesFrecuentesAsync(DateTime? fecha_inicio, DateTime? fecha_fin, int? compra, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_ConsumiblesMasVendidosResult>> SP_ConsumiblesMasVendidosAsync(DateTime? fecha_inicio, DateTime? fecha_fin, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_EntradasRecaudacionXDiaResult>> SP_EntradasRecaudacionXDiaAsync(DateTime? fecha_inicio, DateTime? fecha_fin, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_FuncionesXHorarioResult>> SP_FuncionesXHorarioAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_PeliculasEnCarteleraResult>> SP_PeliculasEnCarteleraAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_PromedioEntradasPorSalaResult>> SP_PromedioEntradasPorSalaAsync(DateTime? fecha_inicio, DateTime? fecha_fin, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_ProximasFuncionesResult>> SP_ProximasFuncionesAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_RecaudacionTotalResult>> SP_RecaudacionTotalAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_RecaudacionXPeliculaResult>> SP_RecaudacionXPeliculaAsync(DateTime? fecha_inicio, DateTime? fecha_fin, int? recaudacion, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_TotalClientesRegistradosResult>> SP_TotalClientesRegistradosAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_TotalEntradasVendidasResult>> SP_TotalEntradasVendidasAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
