// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TP_ProgramaciónII_PIPORAMA.Data.Models
{
    public partial class PromedioEntradasPorSalaResult
    {
        [StringLength(40)]
        public string nom_sala { get; set; }
        public int? funciones { get; set; }
        public int? entradas_vendidas { get; set; }
        public int? cant_butacas { get; set; }
        [Column("ocupacion_promedio", TypeName = "decimal(26,12)")]
        public decimal? ocupacion_promedio { get; set; }
    }
}
