// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TP_ProgramaciónII_PIPORAMA.Data.Models
{
    public partial class RecaudacionXPeliculaResult
    {
        [StringLength(100)]
        public string pelicula { get; set; }
        public double? recaudacion_total { get; set; }
        public int? entradas_vendidas { get; set; }
    }
}
