// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TP_ProgramaciónII_PIPORAMA.Data.Models
{
    public partial class RecaudacónTotalCombosResult
    {
        [StringLength(60)]
        public string nom_combo { get; set; }
        public double? recaudacion_total { get; set; }
    }
}
