// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TP_ProgramaciónII_PIPORAMA.Data.Models
{
    public partial class SP_PeliculasMasVistasResult
    {
        [StringLength(100)]
        public string nom_pelicula { get; set; }
        public int? total_entradas { get; set; }
    }
}
