// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TP_ProgramaciónII_PIPORAMA.Data.Models
{
    public partial class SP_ProximasFuncionesResult
    {
        [StringLength(100)]
        public string nom_pelicula { get; set; }
        [StringLength(40)]
        public string nom_sala { get; set; }
        public DateTime? horario { get; set; }
        [StringLength(20)]
        public string idioma { get; set; }
        [StringLength(20)]
        public string tipo_proyeccion { get; set; }
    }
}
