// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TP_ProgramaciónII_PIPORAMA.Data.Models
{
    public partial class SP_RecaudacónTotalCombosResult
    {
        [StringLength(60)]
        public string nom_combo { get; set; }
        [StringLength(30)]
        public string recaudacion_total { get; set; }
    }
}
