// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TP_ProgramaciónII_PIPORAMA.Data.Models
{
    public partial class FuncionesXHorarioResult
    {
        [StringLength(9)]
        public string franja_horaria { get; set; }
        public int? cantidad_funciones { get; set; }
    }
}
