// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using TP_ProgramaciónII_PIPORAMA.Data.Models;

namespace TP_ProgramaciónII_PIPORAMA.Data.Models
{
    public partial interface IPIPORAMAContextProcedures
    {
        Task<List<ClientesFrecuentesResult>> ClientesFrecuentesAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<ConsumiblesMasVendidosResult>> ConsumiblesMasVendidosAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<EntradasRecaudacionXDiaResult>> EntradasRecaudacionXDiaAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<FuncionesXHorarioResult>> FuncionesXHorarioAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<PeliculasEnCarteleraResult>> PeliculasEnCarteleraAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<PeliculasMasVistasResult>> PeliculasMasVistasAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<PromedioEntradasPorSalaResult>> PromedioEntradasPorSalaAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<ProximasFuncionesResult>> ProximasFuncionesAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<RecaudacionTotalResult>> RecaudacionTotalAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<RecaudacionXPeliculaResult>> RecaudacionXPeliculaAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<RecaudacónTotalCombosResult>> RecaudacónTotalCombosAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<TotalClientesRegistradosResult>> TotalClientesRegistradosAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<TotalEntradasVendidasResult>> TotalEntradasVendidasAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
