// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TP_ProgramaciónII_PIPORAMA.Data.Models
{
    public partial class RecaudacionTotalResult
    {
        [Column("Recaudacion Total")]
        public double? RecaudacionTotal { get; set; }
    }
}
